/*
 * This file is generated by jOOQ.
*/
package task.db.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;

import task.db.enums.TaskStatus;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Task implements Serializable {

    private static final long serialVersionUID = 972186868;

    private Long       id;
    private String     name;
    private String     description;
    private TaskStatus status;
    private Boolean    urgent;
    private Boolean    appeal;
    private Boolean    template;
    private Long       sectionId;
    private Timestamp  creationTime;
    private Timestamp  duetime;
    private String     creatorUsername;

    public Task() {}

    public Task(Task value) {
        this.id = value.id;
        this.name = value.name;
        this.description = value.description;
        this.status = value.status;
        this.urgent = value.urgent;
        this.appeal = value.appeal;
        this.template = value.template;
        this.sectionId = value.sectionId;
        this.creationTime = value.creationTime;
        this.duetime = value.duetime;
        this.creatorUsername = value.creatorUsername;
    }

    public Task(
        Long       id,
        String     name,
        String     description,
        TaskStatus status,
        Boolean    urgent,
        Boolean    appeal,
        Boolean    template,
        Long       sectionId,
        Timestamp  creationTime,
        Timestamp  duetime,
        String     creatorUsername
    ) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.status = status;
        this.urgent = urgent;
        this.appeal = appeal;
        this.template = template;
        this.sectionId = sectionId;
        this.creationTime = creationTime;
        this.duetime = duetime;
        this.creatorUsername = creatorUsername;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public TaskStatus getStatus() {
        return this.status;
    }

    public void setStatus(TaskStatus status) {
        this.status = status;
    }

    public Boolean getUrgent() {
        return this.urgent;
    }

    public void setUrgent(Boolean urgent) {
        this.urgent = urgent;
    }

    public Boolean getAppeal() {
        return this.appeal;
    }

    public void setAppeal(Boolean appeal) {
        this.appeal = appeal;
    }

    public Boolean getTemplate() {
        return this.template;
    }

    public void setTemplate(Boolean template) {
        this.template = template;
    }

    public Long getSectionId() {
        return this.sectionId;
    }

    public void setSectionId(Long sectionId) {
        this.sectionId = sectionId;
    }

    public Timestamp getCreationTime() {
        return this.creationTime;
    }

    public void setCreationTime(Timestamp creationTime) {
        this.creationTime = creationTime;
    }

    public Timestamp getDuetime() {
        return this.duetime;
    }

    public void setDuetime(Timestamp duetime) {
        this.duetime = duetime;
    }

    public String getCreatorUsername() {
        return this.creatorUsername;
    }

    public void setCreatorUsername(String creatorUsername) {
        this.creatorUsername = creatorUsername;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Task (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(description);
        sb.append(", ").append(status);
        sb.append(", ").append(urgent);
        sb.append(", ").append(appeal);
        sb.append(", ").append(template);
        sb.append(", ").append(sectionId);
        sb.append(", ").append(creationTime);
        sb.append(", ").append(duetime);
        sb.append(", ").append(creatorUsername);

        sb.append(")");
        return sb.toString();
    }
}
