/*
 * This file is generated by jOOQ.
*/
package task.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import task.db.enums.EmployeeRank;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = -984486118;

    private String       username;
    private String       password;
    private EmployeeRank rank;
    private Boolean      enabled;

    public User() {}

    public User(User value) {
        this.username = value.username;
        this.password = value.password;
        this.rank = value.rank;
        this.enabled = value.enabled;
    }

    public User(
        String       username,
        String       password,
        EmployeeRank rank,
        Boolean      enabled
    ) {
        this.username = username;
        this.password = password;
        this.rank = rank;
        this.enabled = enabled;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public EmployeeRank getRank() {
        return this.rank;
    }

    public void setRank(EmployeeRank rank) {
        this.rank = rank;
    }

    public Boolean getEnabled() {
        return this.enabled;
    }

    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(username);
        sb.append(", ").append(password);
        sb.append(", ").append(rank);
        sb.append(", ").append(enabled);

        sb.append(")");
        return sb.toString();
    }
}
