/*
 * This file is generated by jOOQ.
*/
package task.db.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import task.db.tables.Employee;
import task.db.tables.records.EmployeeRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmployeeDao extends DAOImpl<EmployeeRecord, task.db.tables.pojos.Employee, String> {

    /**
     * Create a new EmployeeDao without any configuration
     */
    public EmployeeDao() {
        super(Employee.EMPLOYEE, task.db.tables.pojos.Employee.class);
    }

    /**
     * Create a new EmployeeDao with an attached configuration
     */
    public EmployeeDao(Configuration configuration) {
        super(Employee.EMPLOYEE, task.db.tables.pojos.Employee.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(task.db.tables.pojos.Employee object) {
        return object.getUsername();
    }

    /**
     * Fetch records that have <code>username IN (values)</code>
     */
    public List<task.db.tables.pojos.Employee> fetchByUsername(String... values) {
        return fetch(Employee.EMPLOYEE.USERNAME, values);
    }

    /**
     * Fetch a unique record that has <code>username = value</code>
     */
    public task.db.tables.pojos.Employee fetchOneByUsername(String value) {
        return fetchOne(Employee.EMPLOYEE.USERNAME, value);
    }

    /**
     * Fetch records that have <code>email IN (values)</code>
     */
    public List<task.db.tables.pojos.Employee> fetchByEmail(String... values) {
        return fetch(Employee.EMPLOYEE.EMAIL, values);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<task.db.tables.pojos.Employee> fetchByName(String... values) {
        return fetch(Employee.EMPLOYEE.NAME, values);
    }
}
