/*
 * This file is generated by jOOQ.
*/
package task.db;


import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;

import task.db.tables.Employee;
import task.db.tables.StoreSection;
import task.db.tables.Task;
import task.db.tables.TaskEmployee;
import task.db.tables.User;
import task.db.tables.records.EmployeeRecord;
import task.db.tables.records.StoreSectionRecord;
import task.db.tables.records.TaskEmployeeRecord;
import task.db.tables.records.TaskRecord;
import task.db.tables.records.UserRecord;


/**
 * A class modelling foreign key relationships between tables of the <code>public</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<EmployeeRecord> EMPLOYEE_PKEY = UniqueKeys0.EMPLOYEE_PKEY;
    public static final UniqueKey<StoreSectionRecord> STORE_SECTION_PKEY = UniqueKeys0.STORE_SECTION_PKEY;
    public static final UniqueKey<TaskRecord> TASK_PKEY = UniqueKeys0.TASK_PKEY;
    public static final UniqueKey<UserRecord> USER_PKEY = UniqueKeys0.USER_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<EmployeeRecord, UserRecord> EMPLOYEE__EMPLOYEE_USER_FKEY = ForeignKeys0.EMPLOYEE__EMPLOYEE_USER_FKEY;
    public static final ForeignKey<TaskRecord, StoreSectionRecord> TASK__TASK_SECTION_FKEY = ForeignKeys0.TASK__TASK_SECTION_FKEY;
    public static final ForeignKey<TaskRecord, UserRecord> TASK__TASK_USER_FKEY = ForeignKeys0.TASK__TASK_USER_FKEY;
    public static final ForeignKey<TaskEmployeeRecord, TaskRecord> TASK_EMPLOYEE__TASK_EMPLOYEE_TASK_FKEY = ForeignKeys0.TASK_EMPLOYEE__TASK_EMPLOYEE_TASK_FKEY;
    public static final ForeignKey<TaskEmployeeRecord, EmployeeRecord> TASK_EMPLOYEE__TASK_EMPLOYEE_EMPLOYEE_FKEY = ForeignKeys0.TASK_EMPLOYEE__TASK_EMPLOYEE_EMPLOYEE_FKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<EmployeeRecord> EMPLOYEE_PKEY = createUniqueKey(Employee.EMPLOYEE, "employee_pkey", Employee.EMPLOYEE.USERNAME);
        public static final UniqueKey<StoreSectionRecord> STORE_SECTION_PKEY = createUniqueKey(StoreSection.STORE_SECTION, "store_section_pkey", StoreSection.STORE_SECTION.ID);
        public static final UniqueKey<TaskRecord> TASK_PKEY = createUniqueKey(Task.TASK, "task_pkey", Task.TASK.ID);
        public static final UniqueKey<UserRecord> USER_PKEY = createUniqueKey(User.USER, "user_pkey", User.USER.USERNAME);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<EmployeeRecord, UserRecord> EMPLOYEE__EMPLOYEE_USER_FKEY = createForeignKey(task.db.Keys.USER_PKEY, Employee.EMPLOYEE, "employee__employee_user_fkey", Employee.EMPLOYEE.USERNAME);
        public static final ForeignKey<TaskRecord, StoreSectionRecord> TASK__TASK_SECTION_FKEY = createForeignKey(task.db.Keys.STORE_SECTION_PKEY, Task.TASK, "task__task_section_fkey", Task.TASK.SECTION_ID);
        public static final ForeignKey<TaskRecord, UserRecord> TASK__TASK_USER_FKEY = createForeignKey(task.db.Keys.USER_PKEY, Task.TASK, "task__task_user_fkey", Task.TASK.CREATOR_USERNAME);
        public static final ForeignKey<TaskEmployeeRecord, TaskRecord> TASK_EMPLOYEE__TASK_EMPLOYEE_TASK_FKEY = createForeignKey(task.db.Keys.TASK_PKEY, TaskEmployee.TASK_EMPLOYEE, "task_employee__task_employee_task_fkey", TaskEmployee.TASK_EMPLOYEE.TASK_ID);
        public static final ForeignKey<TaskEmployeeRecord, EmployeeRecord> TASK_EMPLOYEE__TASK_EMPLOYEE_EMPLOYEE_FKEY = createForeignKey(task.db.Keys.EMPLOYEE_PKEY, TaskEmployee.TASK_EMPLOYEE, "task_employee__task_employee_employee_fkey", TaskEmployee.TASK_EMPLOYEE.USERNAME);
    }
}
