/*
 * This file is generated by jOOQ.
*/
package task.db;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import task.db.tables.Employee;
import task.db.tables.StoreSection;
import task.db.tables.Task;
import task.db.tables.TaskEmployee;
import task.db.tables.User;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 729008000;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.employee</code>.
     */
    public final Employee EMPLOYEE = task.db.tables.Employee.EMPLOYEE;

    /**
     * The table <code>public.store_section</code>.
     */
    public final StoreSection STORE_SECTION = task.db.tables.StoreSection.STORE_SECTION;

    /**
     * The table <code>public.task</code>.
     */
    public final Task TASK = task.db.tables.Task.TASK;

    /**
     * The table <code>public.task_employee</code>.
     */
    public final TaskEmployee TASK_EMPLOYEE = task.db.tables.TaskEmployee.TASK_EMPLOYEE;

    /**
     * The table <code>public.user</code>.
     */
    public final User USER = task.db.tables.User.USER;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Employee.EMPLOYEE,
            StoreSection.STORE_SECTION,
            Task.TASK,
            TaskEmployee.TASK_EMPLOYEE,
            User.USER);
    }
}
