/*
 * This file is generated by jOOQ.
*/
package task.db;


import javax.annotation.Generated;

import task.db.tables.Employee;
import task.db.tables.StoreSection;
import task.db.tables.Task;
import task.db.tables.TaskEmployee;
import task.db.tables.User;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.employee</code>.
     */
    public static final Employee EMPLOYEE = task.db.tables.Employee.EMPLOYEE;

    /**
     * The table <code>public.store_section</code>.
     */
    public static final StoreSection STORE_SECTION = task.db.tables.StoreSection.STORE_SECTION;

    /**
     * The table <code>public.task</code>.
     */
    public static final Task TASK = task.db.tables.Task.TASK;

    /**
     * The table <code>public.task_employee</code>.
     */
    public static final TaskEmployee TASK_EMPLOYEE = task.db.tables.TaskEmployee.TASK_EMPLOYEE;

    /**
     * The table <code>public.user</code>.
     */
    public static final User USER = task.db.tables.User.USER;
}
